service: serverless-appsync-backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: prod
  region: us-east-2


functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    name: appSyncBookStoreApi
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: us-east-2
      defaultAction: ALLOW
      userPoolId: !Ref cognitoUserPool
    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - type: Query
        field: getBookById
        dataSource: booksTable
      - type: Mutation
        field: createBook
        dataSource: booksTable
    dataSources:
      - type: AMAZON_DYNAMODB
        name: booksTable
        config:
          tableName: !Ref booksTable

resources:
  Resources:
    ${file(resources.yml)}